config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  
  get "about", to: "pages#about"
  get "contact", to: "pages#contact"

  resources :portfolios do
    put :sort, on: :collection
  end
  get 'angular-items', to: "portfolios#angular"
  
  resources :blogs do
  	member do
  	  post :toggle_status
  	end
  end

  root to: "pages#home"
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
	has_many :technologies
	accepts_nested_attributes_for :technologies, reject_if: lambda { |attrs| attrs['name'].blank? }

	include Placeholder
	validates :title, :body, presence: true

  mount_uploader :thumb_image, PortfolioUploader
  mount_uploader :main_image, PortfolioUploader

	scope :angular, lambda { where(subtitle: 'Angular') }
	scope :ruby_on_rails, -> { where(subtitle: 'Ruby on Rails') }
  scope :by_position, -> { order("position ASC") }
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio_item, only: [:edit, :update, :show, :destroy]
  layout "portfolio"
  access all: [:show, :index, :angular], user: {except: [:destroy, :new, :create, :update, :edit]}, site_admin: :all

  def index
    @portfolio_items = Portfolio.by_position
  end

  def sort
    params[:order].each do |key, value|
      Portfolio.find(value[:id]).update(position: value[:postion])
    end
    render nothing: true
  end
  
  def angular
    @angular_portfolio_items = Portfolio.angular
  end

  def show
  end

  def new
    @portfolio_item = Portfolio.new
    3.times { @portfolio_item.technologies.build }
  end
  
  def create
    @portfolio_item = Portfolio.new(portfolio_params)

    if @portfolio_item.save
      redirect_to portfolios_path, notice: "Your portfolio item is now live"
    else
      format.html {render :new}
    end
  end

  def edit
  end

  def update
    if @portfolio_item.update(portfolio_params)
      redirect_to portfolios_path, notice: "Your portfolio item is updated"
    end
  end

  def destroy
    @portfolio_item.destroy
    redirect_to portfolios_path, notice: "Your portfolio item is destroyed"
  end

  private
    def portfolio_params
      params.require(:portfolio).permit(:title,
                                        :subtitle,
                                        :body,
                                        :main_image,
                                        :thumb_image,
                                        technologies_attributes: [:name]
                                        )
    end

    def set_portfolio_item
      @portfolio_item = Portfolio.find(params[:id])
    end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper

  def image_generator(height:, width:)
    "http://via.placeholder.com/#{height}x#{width}"
  end

  def portfolio_img(img, type)
    if img.model[:thumb_image]
      img
    elsif type== 'thumb'
      image_generator(height: '350', width: '200')
    else
      image_generator(height: '600', width: '400')
    end
  end
end

app/views/portfolios/_form.html.erb
<%= form_for(portfolio_item) do |f| %> 
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :subtitle %>
        <%= f.text_field :subtitle, class: 'form-control' %>
      </div>

      <div class="form-group">
        <label class="btn btn-primary">
          upload a main image file <%= f.file_field :main_image, style: 'display:none' %>
        </label>
      </div>

      <div class="form-group">
        <label class="btn btn-primary">
          upload a thumb image file <%= f.file_field :thumb_image, style: 'display:none' %>
        </label>
      </div>
    </div>

    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, class: 'form-control', rows: 13 %>
      </div>
    </div>
    <hr>

    <div class="col-md-12">
      <h2>Technologies Used</h2>
      <ul>
        <%= f.fields_for :technologies do |technology_form|%>
          <li>
            <%= technology_form.label :name %>
            <%= technology_form.text_field :name %>  
          </li>
        <% end %>
      </ul>
      <div class="form-group">
        <%= f.submit 'Save', class: 'btn btn-primary btn-block' %>
      </div>
    </div>
  </div>
<% end %>

app/views/portfolios/_portfolio_item.html.erb
<div class="col-md-4">
	<div class="card mb-4 box-shadow" data-id="<%= item.id %>">
		<%= image_tag portfolio_img(item.thumb_image, 'thumb'), class: "card-img-top"%>
		<div class="card-body">
		  <p class="card-text">
		  	<span><%= link_to item.title, portfolio_path(item.id) %></span>
		  	<%= item.subtitle %>
		  </p>
		</div>
	</div>
</div>

app/views/portfolios/angular.html.erb
<h1>Portfolio Items</h1>

<%= link_to "Create New Item", new_portfolio_path if logged_in?(:site_admin) %>

<% @angular_portfolio_items.each do |item| %>
	<p><%= link_to item.title, portfolio_path(item.id) %></p>
	<p><%= item.subtitle %></p>
	<p><%= item.body %></p>
	<%= image_tag item.thumb_image if !item.thumb_image.nil? %>
	<%= link_to "Edit", edit_portfolio_path(item.id) if logged_in?(:site_admin) %>
	<%= link_to "Delete", portfolio_path(item.id), method: :delete, data: {confirm: "Are you sure?"} if logged_in?(:site_admin) %>
<% end %>

app/views/portfolios/edit.html.erb
<div class="container portfolio-container">

	<h1>Edit this Portfolio Item</h1>
	<%= render 'form', portfolio_item: @portfolio_item %>
	
</div>

app/views/portfolios/index.html.erb
<main role="main">
	<div class="album py-5 bg-light">
    <div class="container">
      <div class="row <%= "sortable" if logged_in?(:site_admin) %>">
				<%= render partial: 'portfolio_item', collection: @portfolio_items, as: :item %>
			</div>
		</div>
	</div>
</main>

app/views/portfolios/new.html.erb
<div class="container portfolio-container">
	<h1>Create a new Portfolio Item</h1>
	<%= render 'form', portfolio_item: @portfolio_item %>	
</div>

app/views/portfolios/show.html.erb
<div class = "container portfolio-container">
	<div class="row">
		<div class="col-md-7">
			<%= image_tag portfolio_img(@portfolio_item.main_image, 'main'), width: '100%' %>
		</div>
		<div class="col-md-5">
			<h1><%= @portfolio_item.title %></h1>
			<hr>
			<em><%= @portfolio_item.subtitle %></em>
			<p><%= @portfolio_item.body %><p>
			<h2>Technologies Used:</h2>
			<% @portfolio_item.technologies.each do |t| %>
				<p> <%= t.name %> </p>
			<% end %>
		</div>
	</div>
</div>